//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_coffee
    {
        public int id_order_coffee { get; set; }
        public Nullable<int> id_order { get; set; }
        public Nullable<int> id_coffee { get; set; }
        public string ml_coffee { get; set; }
    
        public virtual coffee coffee { get; set; }
        public virtual orders orders { get; set; }
    }
}
