//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EslettaEntities : DbContext
    {
        public EslettaEntities()
            : base("name=EslettaEntities")
        {
        }
        public static EslettaEntities _context;
        public static EslettaEntities GetContext() => _context ?? (_context = new EslettaEntities());
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cafe> cafes { get; set; }
        public virtual DbSet<coffee> coffees { get; set; }
        public virtual DbSet<delivery> delivery { get; set; }
        public virtual DbSet<order_coffee> order_coffee { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<product_category> product_category { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<provider> providers { get; set; }
        public virtual DbSet<provider_products> provider_products { get; set; }
        public virtual DbSet<rolee> rolees { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<type_coffe> type_coffe { get; set; }
        public virtual DbSet<userr> userrs { get; set; }
    }
}
